
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgfrnzrrnepzlexhmsld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZnJuenJybmVwemxleGhtc2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTQ4NjEsImV4cCI6MjA2MjgzMDg2MX0.Snrt2saxOaAmJ_I6_G1fEtztGxGtEiDe8FsHv9DyYTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
